import { buttonTailwindStyle } from "./tailwind/button.style";
import { navbarTailwindStyle } from "./tailwind/root/nav.style";
import { headerTailwindStyle } from "./tailwind/root/header.style";
import { inputLabelTailwindStyle } from "./tailwind/inputLabel.style";
import { mainTailwindStyle } from "./tailwind/root/main.style";
export const buttonStyle = buttonTailwindStyle;
export const navbarStyle = navbarTailwindStyle;
export const headerStyle = headerTailwindStyle;
export const inputLabelStyle = inputLabelTailwindStyle;
export const mainStyle = mainTailwindStyle;